### ISSUE TITLE
KeyError: 'jenkinsapi'

### ISSUE THREAD

**Issue by jleyva** [FMCorz/mdk#111]
Traceback (most recent call last):
  File "/opt/local/bin/mdk", line 39, in <module>
    a = runpy.run_module('mdk', None, '__main__')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/moodle-sdk/mdk/__main__.py", line 108, in <module>
    main()
  File "/opt/moodle-sdk/mdk/__main__.py", line 95, in main
    cls = getCommand(cmd)
  File "/opt/moodle-sdk/mdk/commands/__init__.py", line 29, in getCommand
    return getattr(getattr(getattr(__import__('mdk.%s.%s' % ('commands', cmd)), 'commands'), cmd), cls)
  File "/opt/moodle-sdk/mdk/commands/precheck.py", line 28, in <module>
    from ..ci import CI, CIException
  File "/opt/moodle-sdk/mdk/ci.py", line 26, in <module>
    from jenkinsapi import jenkins
  File "/Library/Python/2.7/site-packages/jenkinsapi/__init__.py", line 69, in <module>
    __version__ = pkg_resources.working_set.by_key['jenkinsapi'].version
KeyError: 'jenkinsapi'

**Comment by jleyva** [comment]
Just for the record, if you get this error you need to:

sudo pip uninstall jenkinsapi
sudo easy_install jenkinsapi

Not sure why, but pip installation does not complete correctly the module installation
