### ISSUE TITLE
Request error when after installing MDK

### ISSUE THREAD

**Issue by FMCorz** [FMCorz/mdk#122]
```
marina@marina-desktop:~/repositories$ mdk -v
Traceback (most recent call last):
  File "/usr/local/bin/mdk", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.3.0'))
```

This is the 3rd time this error is reported to me.

**Comment by danpoltawski** [comment]
Yep, experienced the same on Ubuntu 14.04.3 doing:
``
sudo apt-get install python-pip libmysqlclient-dev libpq-dev python-dev
sudo pip install moodle-sdk
mdk init
```

**Comment by FMCorz** [comment]
I'm guessing that requests is somehow installed by default using the version 2.2.1, while JenkinsAPI requires 2.3.0, and as MDK is not using a virtual environment that causes a conflict.
